### ISSUE TITLE
Contravariant functors

### ISSUE THREAD

**Issue by nikita-volkov** [chrisdone/formatting#14]
My understanding of all the Holey business only scratches the surface, so I can't be sure. I have an instinctive feeling that it makes a contravariant functor and a divisible from [the "contravariant" package](https://hackage.haskell.org/package/contravariant). Have you explored this?

**Comment by chrisdone** [comment]
It looks contravarianty, but I'm not sure exactly how.

**Comment by chrisdone** [comment]
Closing so I have zero issues.
