### ISSUE TITLE
How to modify formatter's input?

### ISSUE THREAD

**Issue by neongreen** [chrisdone/formatting#26]
Just for the sake of example, say I want to create a formatter that would print first 8 characters of a string:

``` haskell
first8 :: Format r (String -> r)
first8 = string ??? take 8
```

How would I go about it? I feel that the answer is obvious, but I can't figure it out.

**Comment by chrisdone** [comment]
``` haskell
> format (fitLeft 5) "hel"
"hel"

```

**Comment by neongreen** [comment]
I know about `fitLeft`. I guess I should've explicitly clarified that “first 8 characters” was just an example and the actual use cases for “modify formatter's input” that I encounter don't have standard formatters for them.

Specifically, what I'm looking for is a function of this type:

``` haskell
(???) :: Format r (b -> r) -> (a -> b) -> Format r (a -> r)
```

**Comment by chrisdone** [comment]
Pushed to Hackage `mapf`.

**Comment by neongreen** [comment]
Wow. Thanks!
