### ISSUE TITLE
timeSpecs causes a commitAndReleaseBuffer error

### ISSUE THREAD

**Issue by ivan-m** [chrisdone/formatting#29]
If two `TimeSpec` values are extremely close together (e.g. `(TimeSpec {sec = 43948, nsec = 402952718}, TimeSpec {sec = 43948, nsec = 402964296})`) then the `timeSpecs` formatter will print out a value in microseconds with `" µs"` as the units.  This can hit [this GHC bug](https://ghc.haskell.org/trac/ghc/ticket/8118) resulting in an error message like the following:

```
commitAndReleaseBuffer: invalid argument (invalid character)
```

(I've just spent _way_ too long thinking it was some situation of only happening inside a case statement or something because that's actually where my timings were close enough to cause it to happen.)

Would it be possible to change this to just use `" us"` for portability?

**Comment by chrisdone** [comment]
Sure.
