### ISSUE TITLE
Can `Data.Text.Format` be reexported as an internal module?

### ISSUE THREAD

**Issue by neongreen** [chrisdone/formatting#37]
I'm the author of [`fmt`](hackage.haskell.org/package/fmt). My package uses `Buildable` from `text-format`, along with some of the formatters it provides.

Recently `Buildable` along with everything else from `text-format` was moved to `formatting`, but the formatters themselves (from `Data.Text.Format`) are internal and so I can't use them in my library anymore.

Would you be open to a PR exporting `Data.Text.Format` from `formatting`? E.g. as `Formatting.Internal.Raw`, or maybe even directly from `Formatting.Internal`.

**Comment by chrisdone** [comment]
Sure, `.Raw` sounds fine.
