### ISSUE TITLE
Add sprint :: Format String a -> a

### ISSUE THREAD

**Issue by ocharles** [chrisdone/formatting#38]
Could we have the mentioned function added?

```haskell
sprint = Data.Text.unpack . format
```

but would be rather useful. I'm trying to use `formatting` for all my presentational strings, and some other libraries require `String`s (e.g., `displayException` from the `Exception` class).

**Comment by ocharles** [comment]
Oh, could it be moved into the "Top-level functions" section? I expected to find it there.

**Comment by chrisdone** [comment]
Moved it. :+1:
