### ISSUE TITLE
Lost constraint for `int`?

### ISSUE THREAD

**Issue by qrilka** [chrisdone/formatting#40]
It appears that in 55c7adc3a2b3919c7f50fc1338f9b33ef2a2a342 `Integral` constraint was removed from `int` so now the following is possible:
```
λ> sformat ("an int: "%int%"!") "No way!"
"an int: No way!!"
```
@chrisdone was there some motivation behind that removal that I don't see?

**Comment by chrisdone** [comment]
That was removed at GHC's suggestion of redundant constraints. This was a mistake. I'll add it back at some point.
