### ISSUE TITLE
`int` with `newtype` results in a space leak

### ISSUE THREAD

**Issue by angerman** [chrisdone/formatting#43]
So I've been working on some forward compatibility for a project. And while doing so, bumped formatting from 6.2.5 to 6.3.4. And started observing that our application started consuming memory until it ran out.

I've built the follow reproduction case: https://github.com/angerman/formatting-space-leak

The core being:
```haskell
newtype NewWord = NewWord
    { getNewWord :: Word64
    } deriving (Eq, Ord, Num, Enum, Real, Integral)

instance Buildable NewWord where
  build = bprint ("#"%int)
```

which exhibits the following heap profile: https://github.com/angerman/formatting-space-leak/blob/master/space-repro.svg

Note: having `int = base 10`, seems to produce the expected result.

**Comment by angerman** [comment]
Looking at the folded in definition of `shortest`:
```haskell
shortest :: (Real a) => a -> Builder
shortest = B.build . T.decodeUtf8 . L.toStrict . L.toLazyByteString . L.doubleDec . realToFrac
{-# NOINLINE[0] shortest #-}
```
and from `text-format`
```haskell
shortest :: (Real a) => a -> Builder
shortest = B.build . C.toShortest . realToFrac
{-# RULES "shortest/Double"
    forall x. shortest (x::Double) = B.build (C.toShortest x) #-}
{-# NOINLINE[0] shortest #-}
```
where `C` is `Data.Double.Conversion.Text`.

This might be some unexpected fallout from the dropping of `double-conversion`?

**Comment by chrisdone** [comment]
I'm actually a bit surprised at the definition of `shortest` now that I look at it. It must have come up from a big refactor. I think we could drop most of those intermediate functions.

**Comment by chrisdone** [comment]
Let me load up your repro project and I'll fix this.

**Comment by chrisdone** [comment]
Oh, wait:

```haskell
instance Buildable NewWord where
  build = bprint ("#"%int)
```

Your instance is an infinite loop! `int :: Buildable a => F.Format r (a -> r)`

**Comment by chrisdone** [comment]
Change it to:
```haskell
instance Buildable NewWord where
  build = bprint ("#"%int) . getNewWord
```

**Comment by angerman** [comment]
The thing I don’t fully understand is: why did this work with 6.2.5?

**Comment by angerman** [comment]
I’ll update the repro in ~30min to illustrate, that the same code with a minor change in imports did terminate with 6.2.5, and just the version bump resulted in the illustrated behavio

**Comment by chrisdone** [comment]
That was using `T.shortest`: http://hackage.haskell.org/package/formatting-6.2.5/docs/src/Formatting-Formatters.html#int from text-format.

It was based on `Integral`, now it's using the `Buildable` instance. Sorry that it bit you, that's a pain in the arse. 

Pretty tricky maintenance issue when classes change. :thinking:

**Comment by angerman** [comment]
Sorry to bother you more about this :(

right now the definitions of `build` and `int` are identical.
https://github.com/chrisdone/formatting/blob/23cd3950d0a1a02af11a8362b4013bcf836a5a25/src/Formatting/Formatters.hs#L106-L112

And also looking at #40, can we maybe bring back `int` as
```haskell
int :: Integral a => Format r (a -> r) 
```

similar to what `bin` and `oct` are?

https://github.com/chrisdone/formatting/blob/23cd3950d0a1a02af11a8362b4013bcf836a5a25/src/Formatting/Formatters.hs#L220-L230

PS: also note that `asInt` returns `1.23456789e8` for `123456789`.

**Comment by chrisdone** [comment]
If you redefine `int` as `base 10`, does this fix the problem for you?

**Comment by angerman** [comment]
That's basically what I did here: https://github.com/angerman/formatting/commit/a922965aa58d523feb3174ed994f12b4c4788719

and have been using for the last few hours.

**Comment by chrisdone** [comment]
OK, can you PR that and I'll merge it?

**Comment by angerman** [comment]
Sure. Will do after dinner.
