### ISSUE TITLE
Unsigned values have spurious "-" prefix

### ISSUE THREAD

**Issue by edsko** [chrisdone/formatting#45]
For instance, building "0 :: Word64" results in "-0". Problem is that the special case in `decimal` for `minBound` only works for signed values. 

(EDIT: it only works for _signed_ values, not _unsigned_ values :)

**Comment by chrisdone** [comment]
I think this is fixed on the latest version.
```haskell
> :!grep version formatting.cabal
version:             6.3.7
> format int (0 :: Word64)
"0"
```
